### ISSUE TITLE
Error with automated appservice yaml creation (develop branch)

### ISSUE THREAD

**Issue by neurocis** [matrix-org/matrix-appservice-irc#250]
Automated creation of appservice yaml in develop yields error with reg.setRateLimited:

```
(.synapse)root@synapse:~/matrix-appservice-irc# node app.js -r -f appservice-registration-irc.yaml2 -u "http://localhost:9999" -c config.yaml -l IRC_GeekShed
Loading config file /root/matrix-appservice-irc/config.yaml
Fatal TypeError: reg.setRateLimited is not a function
    at Object.<anonymous> (/root/matrix-appservice-irc/lib/main.js:92:9)
    at next (native)
    at tryCatcher (/root/matrix-appservice-irc/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/root/matrix-appservice-irc/node_modules/bluebird/js/release/generators.js:97:49)
    at Object.generateRegistration (/root/matrix-appservice-irc/node_modules/bluebird/js/release/generators.js:201:15)
    at Cli.generateRegistration (/root/matrix-appservice-irc/app.js:18:14)
    at Cli._generateRegistration (/root/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:171:46)
    at Cli.run (/root/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:117:14)
    at Object.<anonymous> (/root/matrix-appservice-irc/app.js:28:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

Checking back to master branch produces the yaml w/o error.

**Comment by lukebarnard1** [comment]
Thanks for letting us know! Looks like this was introduced with #246. We've threaded through all the version numbers now through various projects, so `npm install` on the `develop` branch Should Just Work :+1:

**Comment by lukebarnard1** [comment]
Appears to be fixed
